var
setActive=function(){$(this).parent('.animation_accordeon_block').toggleClass('close');},closeTrigger=function(){$(this).addClass('close');};function valid_email(val){var reg=new RegExp(/@/);var result=reg.test(val);return result;};function universalCheck(arr,param){for(var i=0;i<arr.length;i++){if(!!arr[i]==!!param){return true};}return false};function blockCheck(block,param){var
arr=[];block.each(function(index){arr.push($(this).val());});return universalCheck(arr,param);};function CheckForm(aim,message){var
checkList=1;if(blockCheck(aim.find('input.must'),0)){alert('Есть незаполненные поля!')
checkList=0}aim.find("input.email").each(function(e){var
email=$(this);if(valid_email(email.val())!=true){alert('Неверный e-mail');email.value='';checkList=0};});if(checkList){aim.submit();}return false;};function Gid(id){return document.getElementById(id);};function calc(){var aim=Gid('square'),aim2=Gid('result_block');if(!aim||aim.value==''){aim2.style.display='none';return false;}var num=1*aim.value;Gid('rez').innerHTML=Math.ceil(num/30);aim2.style.display='';return false;};function Go(url){document.location=url;};function hm(a,m){var
i,r=[];for(i=0;i<a.length;i++)r[i]=a[i][0]+'@'+a[i][1]+'.'+a[i][2];return(m!='')?('<a href="mailto:'+r.join(';')+'">'+m+'</a>'):(r);};function parseGetParams(){var
$_GET={},__GET=window.location.search.substring(1).split("&");for(var i=0;i<__GET.length;i++){var getVar=__GET[i].split("=");$_GET[getVar[0]]=typeof(getVar[1])=="undefined"?"":getVar[1];}return $_GET;};var slider=(function(){var
initialize=function(){if($('#slider').length){_loadImg();_slider();}},_loadImg=function(){$('#slider .slider').each(function(i){var
$this=$(this),$image=$this.find('.slider_img')
src=$image.data('src');if(i==0){$image.attr('src',src);}});},_slider=function(){$('#slider').cycle({nowrap:0,fx:'scrollDown',speed:1000,timeout:5000,pager:'#nav',pagerAnchorBuilder:function(idx,slide){var
$slide=$(slide).find('.slider_img'),tm_src=$slide.attr('data-tm'),tm_img='',tm_name='';if(typeof(tm_src)!='undefined'){tm_img='<span class="b_baner"><img src = " '+tm_src+' " /></span>';};tm_name='<span class="b_title">'+$slide.attr('alt')+'</span>';return'<a class="slide_pager" href = "#">'+tm_name+tm_img+'</a> ';},before:function(curr,next,opts){var
nextImg=$(next).find('.slider_img'),imgSrc=$(next).find('.slider_img').attr('data-src');if(imgSrc){nextImg.attr('src',imgSrc);nextImg.attr('data-src','');}}});};return{init:initialize};}());var where=(function(){var
initialize=function(){if($('#good_type').length){_check();_search();}},_check=function(){var
query=parseGetParams(),$select=$('#good_type');if(query['sheetrock']=='true'){$select.find('option[value=sheetrock]').attr('selected','selected');}if(query['danogips']=='true'){$select.find('option[value=danogips]').attr('selected','selected');}},_search=function(){$('.find_city').autocomplete({source:'/autocomplete_city.html?good='+$('#good_type').selectedIndex,minLength:2,select:function(event,ui){var
url=ui.item.url;if(url!='#'){location.href=url;}},html:true,open:function(event,ui){$('.ui-autocomplete').css('z-index',1000);}}).focus(function(){$(this).autocomplete('search','');});};return{init:initialize}}());var videoOLD=(function(){var
initialize=function(){_styles();_heights();_tags();_more();},_heights=function(){$('.video__list .video__item:not(.hidden)').matchHeight({byRow:true});},_styles=function(){$('.video__list .video__item').each(function(){var
$this=$(this);$this.removeClass('_odd');$this.removeClass('_even');});$('.video__list .video__item:not(.hidden)').each(function(index){var
$this=$(this),$list=$this.closest('.video__list');if(index%2==0){$this.addClass('_odd');}else{$this.addClass('_even');}});if($('.video__item._wide12:not(.hidden)').length){$('.video__list').addClass('invert');}else{$('.video__list').removeClass('.invert');}},_tags=function(){$('.tags_item').each(function(){var
$this=$(this),$num=$this.find('.num'),current=$this.data('id'),$items=$this.closest('.video').find('.video__item');var
$show,$hide;$show=$items.filter(function(index){if($(this).attr('data-tags').indexOf(current)!==-1){return true;}else{return false;}});$hide=$items.filter(function(index){if($(this).attr('data-tags').indexOf(current)==-1){return true;}else{return false;}});if($show.length){$this.removeClass('hidden');$num.html($show.length);}else{$this.addClass('hidden');}$this.on('click',function(){var
$more=$('.video__list_more');$items.removeClass('_wide8').removeClass('_wide12');$items.removeAttr('style');$more.hide();if($this.hasClass('_all')){$('.tags_item._active').removeClass('_active');$items.removeClass('hidden');$items.find('_text').addClass('hidden');}else{$this.addClass('_active').siblings().removeClass('_active');$show.removeClass('hidden');$hide.addClass('hidden');}$(document).ready(function(){_heights();_styles();});});});},_more=function(){$('.video__list_more').each(function(){var
$this=$(this),$num=$this.find('.num'),$button=$this.find('.video__list_more_button'),$items=$this.closest('.video').find('.video__item.hidden'),count=$items.length;if(count>0){$num.html(count);$this.show();}else{$this.hide();}$button.click(function(){if(count>0){$items.removeClass('hidden');_heights();}$this.hide();});});};return{init:initialize}}());var video=(function(){var
initialize=function(){if($('.video__list').length){_init();}},_init=function(){var
$grid=$('.video__list2').isotope({itemSelector:'.video__item',percentPosition:true,layoutMode:'masonry',masonry:{columnWidth:4,gutter:20}});_setTags();_filter();_more();},_setTags=function(){$('.video__tags .tags_item').each(function(){var
$this=$(this),selector=$this.attr('data-filter'),num=0;if($(selector).length){num=$(selector).length;}if(!$this.hasClass('_all')){if($this.find('.num').length){$this.find('.num').html(num);}else{$this.append(' (<span class="num">'+num+'</span>)');}}});},_filter=function(){$('.video__tags .tags_item').on('click',function(){var
$this=$(this),$grid=$('.video__list'),selector=$this.attr('data-filter');$this.addClass('_active').siblings().removeClass('_active');if($this.hasClass('_all'))$('.tags_item._active').removeClass('_active');$grid.isotope({filter:selector});});},_more=function(){$('.video__list_more').show();if(!$('.video__item.hidden').is('*'))$('.video__list_more_button').hide();$('.video__list_more_button').on('click',function(){var
elems=[],$grid=$('.video__list'),filtered=$('.tags_item._active').is('*');for(var i=0;i<6;i++){if(filtered){var filter=$('.tags_item._active').data('filter');var $elem=$('.video__item.hidden:not('+filter+'):first').clone();$('.video__item.hidden:not('+filter+'):first').remove();}else{var $elem=$('.video__item.hidden:first').clone();$('.video__item.hidden:first').remove();}$elem.toggleClass('hidden');elems.push($elem[0]);}$grid.isotope('insert',elems);if(!$('.video__item.hidden').is('*'))$(this).hide();_setTags();});};return{init:initialize}}());var cookieNotice=(function(){var
initialize=function(){_setNotice();},_setNotice=function(){var
$policy=$('#policy_agreement'),$close=$('.policy__close');if(typeof(Cookies.get('policy_agreement'))=='undefined'||Cookies.get('policy_agreement')!=='yes'){$policy.fadeIn('600');}$close.click(function(){$policy.animate({height:0});Cookies.set('policy_agreement','yes',{expires:30});});};return{init:initialize}}());$(document).ready(function(){var
query=parseGetParams();slider.init();where.init();video.init();cookieNotice.init();$('[data-tip]').tipr();$('.pro__item').matchHeight();$('.fancybox').fancybox({openMethod:'zoomIn'});$('.thickbox').fancybox({openMethod:'zoomIn'});$('input[placeholder], textarea[placeholder]').placeholder();$('.conventionalized_form select, .conventionalized_form input:checkbox, .conventionalized_form input:radio, .conventionalized_form input:file').uniform();$('.callback_form input[type=submit]').on('click',function(){var
$this=$(this),$form=$this.closest('form'),checkList=1;if(blockCheck($form.find('input.must'),0)){alert('Есть незаполненные поля!')
checkList=0}$form.find("input.email").each(function(e){var
email=$(this);if(valid_email(email.val())!=true){alert('Неверный e-mail');email.value='';checkList=0};});if(checkList){$form.submit();}return false;});$('.animation_accordeon_block').each(closeTrigger);$('.animation_accordeon_block .switcher').click(setActive);if(window.location.pathname=='/gde_kupit.html'){$('body').append('<img src="//ads.adfox.ru/1424/tracePoint?p7=nwfl&amp;p8=c" width="0" height="0" alt="">');}if($('body').hasClass('map_page')){$('body').append('<div class="map_title" id="stores-map-tip"></div>');$('#stores-map area').hover(function(e){var
offset,parent_offset;var
subj_id=$(this).attr('data-subject');$('#stores-map img.region:not(.current)').removeClass('active');$('#region-img'+subj_id).addClass('active');offset=$(this).offset();parent_offset=$(this).parent().offset();$('#stores-map-tip').text($(this).attr('alt'));$('#stores-map-tip').show();$('#stores-map-tip').css({left:e.pageX+10});$('#stores-map-tip').css({top:e.pageY-10});},function(){$('#stores-map img.region:not(.current)').removeClass('active');$('#stores-map-tip').hide();});$('#stores-map area').click(function(e){var
$this=$(this),url=$this.attr('href');if(url=='#'){return false;}});$('#stores-map').mouseout(function(){$('#stores-map img.region:not(.current)').removeClass('active');$('#stores-map-tip').hide();});}if(window.location.href.indexOf('/produktsiya_sheetrock')!=-1||window.location.href.indexOf('/produktsiya_sheetrock/gotovie_shpatlevki/super_finish.html')!=-1||window.location.href.indexOf('/produktsiya_sheetrock/gotovie_shpatlevki/fill_finish_ligh­­t.html')!=-1||window.location.href.indexOf('/produktsiya_sheetrock/gotovie_shpatlevki.html')!=-1||window.location.href.indexOf('/produktsiya_sheetrock.html')!=-1){var
showcase;$('.side_panel').append('<div class="showcase"><a class="showcase_link" href="/dlya_professionalov.html"></a><div id="showcase"></div></div>');showcase=$('#showcase');swfobject.embedSWF('/files/240_400_danogips.swf','showcase',240,400,10);}$('.faq_q').click(function(){var
$this=$(this);$this.toggleClass('active');$this.next('.faq_a').slideToggle();});$('.vac_q').click(function(){var
$this=$(this);$this.toggleClass('active');$this.next('.vac_a').slideToggle();});if(!$('.c-tab').eq(0).hasClass('active')){$('.c-tab').eq(0).addClass('active').siblings().removeClass('active');}if(!$('.c-tab-content').eq(0).hasClass('active')){$('.c-tab-content').eq(0).addClass('active').siblings().removeClass('active');}$('.c-tab').click(function(){var
$this=$(this),$content=$this.closest('.c-tabs').nextAll('.c-tabs-content');if(!$this.hasClass('active')){$this.addClass('active').siblings().removeClass('active');$content.find('>.c-tab-content').eq($this.index()).fadeIn(150).siblings('.c-tab-content').hide();}});$('.tab-opt-tit').click(function(){var
$this=$(this),index=$this.index();if(!$this.hasClass('active')){$this.addClass('active').siblings().removeClass('active');$this.closest('.main').find('.tab-opt').eq(index).addClass('active').siblings().removeClass('active');map.removeAllOverlays();if($this.parent().find('>.tab-opt-tit').index(this)){for(var i=0;i<window.addressesOpt.length;i++){addAdress(window.addressesOpt[i].adress,'','',window.addressesOpt[i].name,window.addressesOpt[i].phone,window.addressesOpt[i].type,window.addressesOpt[i].icons);}}else{for(var i=0;i<window.addressesRoznica.length;i++){addAdress(window.addressesRoznica[i].adress,'','',window.addressesRoznica[i].name,window.addressesRoznica[i].phone,window.addressesRoznica[i].type,window.addressesRoznica[i].icons);}}}});$('.selectProductType').SumoSelect({captionFormat:'{0} выбрано',captionFormatAllSelected:'Вся продукция',});$('.selectProductCity').SumoSelect({search:true,searchText:'Найти',noMatch:'Не найдено "{0}"'});window.addressesRoznica=window.addressesRoznica||[];window.addressesOpt=window.addressesOpt||[];for(var i=0;i<window.addressesRoznica.length;i++){addAdress(window.addressesRoznica[i].adress,'','',window.addressesRoznica[i].name,window.addressesRoznica[i].phone,window.addressesRoznica[i].type,window.addressesRoznica[i].icons);}if(query['success']==='1'){if(typeof(yaCounter33387977)!=='undefined '){yaCounter33387977.reachGoal('SENDFORM');}if(typeof(ga)!=='undefined '){ga('send','event','forma','otpravka');}}$('.buy_link.but').on('click',function(){if(typeof(yaCounter33387977)!=='undefined '){yaCounter33387977.reachGoal('GDE_KUPIT');}if(typeof(ga)!=='undefined '){ga('send','event','GDE_KUPIT','click');}});$('.event__info_link').on('click',function(){if(typeof(yaCounter33387977)!=='undefined '){yaCounter33387977.reachGoal('regeventbutton');}});$('.form__event').on('submit',function(){if(typeof(yaCounter33387977)!=='undefined '){yaCounter33387977.reachGoal('formeventsend');}if(typeof(ga)!=='undefined '){ga('send','event','formeventsend','click');}});$('#events_more').click(function(e){e.stopPropagation;var
$this=$(this),$list=$('#events_passed'),date=$this.data('date'),parent=$this.data('parent'),offset=parseInt($this.data('offset')),href=$this.data('href'),step=parseInt($this.data('step')),total=parseInt($this.data('total')),query={action:'getEvents',parents:parent,limit:step,tvFilters:date,offset:offset,};$.ajax({type:'POST',url:'/ajax',data:query,success:function(data){var
response=$('<div />').html(data);offset+=step;response.find('script').remove();response.find('link').remove();response.find('.fm-panel').remove();response=response.html();$list.append(response);$this.data('offset',offset);if($list.find('.events__item').length>=total){$this.hide();}},error:function(){console.log('AJAX error');}});return false;});$('.pseudo').click(function(e){var
$this=$(this),target=$this.data('href'),offset=$(target).offset().top;e.preventDefault;offset=offset-$('.menu_top').height();$('html, body').animate({scrollTop:offset},800);return false;});$('.related_articles_container').addClass('rel_count_'+$('.related_articles_container .related_article_item').length);$('.related_article_item:first').addClass('active');$('.related_desc').html($('.related_article_item:first .hidden').html());$('.related_article_item').not('.active').click(function(){$('.related_article_item.active').toggleClass('active');$(this).toggleClass('active');$('.related_desc').html($(this).find('.hidden').html());});$(window).scroll(function(){var
isScrolled=$(window).scrollTop()>20;$('.header--wrapper').toggleClass('animated',isScrolled);$('.main').toggleClass('padded',isScrolled);});});